---

- name: create dynamic inventory to critical memory
  hosts: localhost
  gather_facts: false
  tasks:
  - name: Add hosts to critical memory
    add_host:
      name: item
      groups: critical_inventory
      gather_facts: false
    
- name: reboot routers
  hosts: critical_inventory
  become: yes
  vars:
    ansible_command_timeout: 10
  tasks:
    - name: Reload
      cisco.ios.ios_command:
        commands:
          - command: "reload"
            prompt:
              - "Save system"
              - "Proceed with reload"
            answer:
              - "yes"
              - "\n"
      register: reload_output          